In [76]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from prettytable import PrettyTable

In [77]:
df2 = pd.read_csv('dataset\iowa_liquor_sales_2025_1262_rows_part_0002.csv')
df3 = pd.read_csv('dataset\iowa_liquor_sales_2025_1262_rows_part_0003.csv')
df4 = pd.read_csv('dataset\iowa_liquor_sales_2025_1262_rows_part_0004.csv')
df5 = pd.read_csv('dataset\iowa_liquor_sales_2025_1262_rows_part_0005.csv')

<>:1: SyntaxWarning: invalid escape sequence '\i'
<>:2: SyntaxWarning: invalid escape sequence '\i'
<>:3: SyntaxWarning: invalid escape sequence '\i'
<>:4: SyntaxWarning: invalid escape sequence '\i'
<>:1: SyntaxWarning: invalid escape sequence '\i'
<>:2: SyntaxWarning: invalid escape sequence '\i'
<>:3: SyntaxWarning: invalid escape sequence '\i'
<>:4: SyntaxWarning: invalid escape sequence '\i'
C:\Users\Cetaking\AppData\Local\Temp\ipykernel_63844\926730239.py:1: SyntaxWarning: invalid escape sequence '\i'
  df2 = pd.read_csv('dataset\iowa_liquor_sales_2025_1262_rows_part_0002.csv')
C:\Users\Cetaking\AppData\Local\Temp\ipykernel_63844\926730239.py:2: SyntaxWarning: invalid escape sequence '\i'
  df3 = pd.read_csv('dataset\iowa_liquor_sales_2025_1262_rows_part_0003.csv')
C:\Users\Cetaking\AppData\Local\Temp\ipykernel_63844\926730239.py:3: SyntaxWarning: invalid escape sequence '\i'
  df4 = pd.read_csv('dataset\iowa_liquor_sales_2025_1262_rows_part_0004.csv')
C:\Users\Cetaking\AppData\Local\Temp\ipykernel_63844\926730239.py:4: SyntaxWarning: invalid escape sequence '\i'
  df5 = pd.read_csv('dataset\iowa_liquor_sales_2025_1262_rows_part_0005.csv')

In [78]:
table = PrettyTable()
table.field_names = ["df2", "df3", "df4", "df5"]

rows = []
for col_name in df2.columns:
    rows.append([df2[col_name].dtype, df3[col_name].dtype if col_name in df3.columns else "", df4[col_name].dtype if col_name in df4.columns else "", df5[col_name].dtype if col_name in df5.columns else ""])

table.add_rows(rows)
print(table)

+---------+---------+---------+---------+
|   df2   |   df3   |   df4   |   df5   |
+---------+---------+---------+---------+
|  object |  object |  object |  object |
|  object |  object |  object |  object |
|  int64  |  int64  |  int64  |  int64  |
|  object |  object |  object |  object |
|  object |  object |  object |  object |
|  object |  object |  object |  object |
| float64 | float64 | float64 | float64 |
| float64 | float64 | float64 | float64 |
|  object |  object |  object |  object |
|  int64  |  int64  |  int64  |  int64  |
|  object |  object |  object |  object |
|  int64  |  int64  |  int64  |  int64  |
|  object |  object |  object |  object |
|  int64  |  int64  |  int64  |  int64  |
|  object |  object |  object |  object |
|  int64  |  int64  |  int64  |  int64  |
|  int64  |  int64  |  int64  |  int64  |
| float64 | float64 | float64 | float64 |
| float64 | float64 | float64 | float64 |
|  int64  |  int64  |  int64  |  int64  |
| float64 | float64 | float64 | float64 |
| float64 | float64 | float64 | float64 |
| float64 | float64 | float64 | float64 |
+---------+---------+---------+---------+

In [79]:
big_DF = [df2, df3, df4, df5]
for frame in big_DF:
    print(frame.shape)
    print(frame.isnull().sum())

(819163, 23)
invoice_id                  0
ordered_on                  0
store_no                    0
store_name                  0
store_address             379
store_city                379
store_zip_code            379
county_fips_code          379
county_name               379
category_code               0
category_name               0
vendor_number               0
vendor_name                 0
item_no                     0
im_desc                     0
pack                        0
bottle_volume_ml            0
state_bottle_cost      632646
state_bottle_retail    632646
sales_bottles               0
sales_dollars               0
sales_liters                0
sales_gallons               0
dtype: int64
(374648, 23)
invoice_id               0
ordered_on               0
store_no                 0
store_name               0
store_address          187
store_city             187
store_zip_code         187
county_fips_code       187
county_name            187
category_code            0
category_name            0
vendor_number            0
vendor_name              0
item_no                  0
im_desc                  0
pack                     0
bottle_volume_ml         0
state_bottle_cost        0
state_bottle_retail      0
sales_bottles            0
sales_dollars            0
sales_liters             0
sales_gallons            0
dtype: int64
(715926, 23)
invoice_id               0
ordered_on               0
store_no                 0
store_name               0
store_address          779
store_city             779
store_zip_code         779
county_fips_code       779
county_name            779
category_code            0
category_name            0
vendor_number            0
vendor_name              0
item_no                  0
im_desc                  0
pack                     0
bottle_volume_ml         0
state_bottle_cost        0
state_bottle_retail      0
sales_bottles            0
sales_dollars            0
sales_liters             0
sales_gallons            0
dtype: int64
(443879, 23)
invoice_id               0
ordered_on               0
store_no                 0
store_name               0
store_address          489
store_city             489
store_zip_code         489
county_fips_code       489
county_name            489
category_code            0
category_name            0
vendor_number            0
vendor_name              0
item_no                  0
im_desc                  0
pack                     0
bottle_volume_ml         0
state_bottle_cost        0
state_bottle_retail      0
sales_bottles            0
sales_dollars            0
sales_liters             0
sales_gallons            0
dtype: int64

In [80]:
df2.head(1)

,invoice_id,ordered_on,store_no,store_name,store_address,store_city,store_zip_code,county_fips_code,county_name,category_code,...,item_no,im_desc,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,sales_bottles,sales_dollars,sales_liters,sales_gallons
0,INV-81168500003,2025-04-01,10420,"FAREWAY STORES, INC. #247 / HULL",640 BLACK FOREST RD,HULL,51239.0,19167.0,SIOUX,1011200,...,16651,BARDSTOWN BOURBON ORIGIN SERIES KENTUCKY STRAI...,6,750,NaN,NaN,2,75.0,1.5,0.39

In [81]:
df2[['state_bottle_cost','state_bottle_retail','sales_bottles','sales_dollars']].head(5)

   state_bottle_cost  state_bottle_retail  sales_bottles  sales_dollars
0                NaN                  NaN              2          75.00
1                NaN                  NaN              1        2250.00
2                NaN                  NaN              2          82.50
3                NaN                  NaN              1         155.96
4                NaN                  NaN              3         123.72

In [82]:
df3.drop(df3.columns[[2,3,4,5]], axis=1).head(4)

,invoice_id,ordered_on,store_zip_code,county_fips_code,county_name,category_code,category_name,vendor_number,vendor_name,item_no,im_desc,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,sales_bottles,sales_dollars,sales_liters,sales_gallons
0,INV-84926600100,2025-07-29,50263.0,19049.0,DALLAS,1081200,CREAM LIQUEURS,205,E & J GALLO WINERY,80487,TIPPY COW VANILLA SOFT SERVE,6,750,11.00,16.50,6,99.00,4.50,1.18
1,INV-84926600037,2025-07-29,50263.0,19049.0,DALLAS,1041200,FLAVORED GIN,796,173 CRAFT DISTILLERY,32701,173 CRAFT DISTILLERY HONEY LEMON FLAVORED GIN,6,750,18.00,27.00,6,162.00,4.50,1.18
2,INV-84926400023,2025-07-29,50263.0,19049.0,DALLAS,1062500,FLAVORED RUM,35,BACARDI USA INC,43138,BACARDI LIMON,6,1750,14.99,22.49,3,67.47,5.25,1.38
3,INV-84926600065,2025-07-29,50263.0,19049.0,DALLAS,1062500,FLAVORED RUM,305,MHW LTD,43869,KASAMA SMALL BATCH RUM 7YR,6,750,13.50,20.25,6,121.50,4.50,1.18

In [83]:
df3 = df3.drop(columns=df3.columns[2:6])
df3

,invoice_id,ordered_on,store_zip_code,county_fips_code,county_name,category_code,category_name,vendor_number,vendor_name,item_no,im_desc,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,sales_bottles,sales_dollars,sales_liters,sales_gallons
0,INV-84926600100,2025-07-29,50263.0,19049.0,DALLAS,1081200,CREAM LIQUEURS,205,E & J GALLO WINERY,80487,TIPPY COW VANILLA SOFT SERVE,6,750,11.00,16.50,6,99.00,4.50,1.180000
1,INV-84926600037,2025-07-29,50263.0,19049.0,DALLAS,1041200,FLAVORED GIN,796,173 CRAFT DISTILLERY,32701,173 CRAFT DISTILLERY HONEY LEMON FLAVORED GIN,6,750,18.00,27.00,6,162.00,4.50,1.180000
2,INV-84926400023,2025-07-29,50263.0,19049.0,DALLAS,1062500,FLAVORED RUM,35,BACARDI USA INC,43138,BACARDI LIMON,6,1750,14.99,22.49,3,67.47,5.25,1.380000
3,INV-84926600065,2025-07-29,50263.0,19049.0,DALLAS,1062500,FLAVORED RUM,305,MHW LTD,43869,KASAMA SMALL BATCH RUM 7YR,6,750,13.50,20.25,6,121.50,4.50,1.180000
4,INV-84926600059,2025-07-29,50263.0,19049.0,DALLAS,1062500,FLAVORED RUM,370,PERNOD RICARD USA,42718,MALIBU COCONUT,6,1750,16.49,24.74,12,296.88,21.00,5.540000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374643,INV-868279,2025-09-22,50315.0,19153.0,POLK,1011200,STRAIGHT BOURBON WHISKIES,65,JIM BEAM BRANDS,27783,JIM BEAM APPLE,12,750,11.50,17.25,12,207.00,9.00,2.377548
374644,INV-868279,2025-09-22,50315.0,19153.0,POLK,1011200,STRAIGHT BOURBON WHISKIES,65,JIM BEAM BRANDS,27410,JIM BEAM HONEY,12,750,11.50,17.25,12,207.00,9.00,2.377548
374645,INV-868390,2025-09-22,50312.0,19153.0,POLK,1011200,STRAIGHT BOURBON WHISKIES,65,JIM BEAM BRANDS,19061,JIM BEAM MINI,12,50,7.00,10.50,3,31.50,0.15,0.039626
374646,INV-868379,2025-09-22,50314.0,19153.0,POLK,1011200,STRAIGHT BOURBON WHISKIES,65,JIM BEAM BRANDS,28279,JIM BEAM PEACH,12,750,11.50,17.25,12,207.00,9.00,2.377548
374647,INV-868282,2025-09-22,50321.0,19153.0,POLK,1011200,STRAIGHT BOURBON WHISKIES,65,JIM BEAM BRANDS,22779,JIM BEAM PINEAPPLE,12,750,11.50,17.25,12,207.00,9.00,2.377548

In [ ]:
# let  create a new dataset derivated from the first but will 
# have as column : 
# invoice_id	
# ordered_on
# - Sales = sales_dollars
#  - Purchases = sales_bottles	
#   - tax adjustements
#   - VAT returns

new_dataset = df2.copy()
col_keep=['invoice_id', 'ordered_on', 'sales_dollars', 'sales_bottles']
for col in new_dataset:
    if col not in col_keep:
        new_dataset = new_dataset.drop(columns=col)
print(new_dataset.dtypes)

Tax = 0.15
VAT_returns = 
def new_dataset_cal(tax, VAT):
    new_dataset['Tax_col'] = new_dataset['sales_dollars']*tax
    
    return new_dataset

invoice_id        object
ordered_on        object
sales_bottles      int64
sales_dollars    float64
dtype: object

: